### ISSUE TITLE
Add option to disable continuous error message

### ISSUE THREAD

**Issue by FuzionZero** [MaterialFoundry/MaterialDeck#69]
Would it be possible to add a setting to change, or perhaps just disable, the repeating error message when the server app is not running? I would prefer not to either have the the server app running every time I am just working in Foundry, or disable the module. Would be good to have the option for it to just gave the error once when Foundry is launched. Thanks.

**Comment by mikewo** [comment]
I added the following script Macro to one of my Macros bars to handle this. It toggles the enabled setting in the modules config. So, if I'm seeing the error, or if none of the commands are working, I just execute the macro to toggle. Note that it will force a reload, but the same thing happens if you go through the configuration screen as well.

```
var deckEnabled = game.settings.get("MaterialDeck", "Enable");
if (deckEnabled) {
  game.settings.set("MaterialDeck", "Enable", false);
} else {
  game.settings.set("MaterialDeck", "Enable", true);
}
```

There's probably a nicer way to handle this, but this was my first venture into digging into the macros for Foundry affecting modules.

**Comment by FuzionZero** [comment]
Hopefully this option can be added, but this is a nice workaround until then.

Thanks!

**Comment by CDeenen** [comment]
The latest version allows you to define how many of those messages you get in the module settings
