### ISSUE TITLE
Streamdeck: Function Turn Display, Alignment problem

### ISSUE THREAD

**Issue by cirkusapan** [MaterialFoundry/MaterialDeck#72]
The alinement of the text on the Streamdeck buttons seems to be off in the function "Turn display", Looks fine when you use both on the same button but when you separate them it seems that there's a space after "turn " and an extra row after indicated round.

![2021-05-20 11_22_50-Window](https://user-images.githubusercontent.com/34601914/118954132-c39ee680-b95d-11eb-80d7-5186e70da9de.png)

**Comment by CDeenen** [comment]
I am not sure about the space after 'turn'. It doesn't appear to be in the code, but I'll dig a little deeper. However, I have noticed that the alignment between the text and the number changes when you change the font size, so it might be due to something the Stream Deck does, which I cannot change.

The empty line after 'round' is a bug, so I'll get that sorted out in the next update.

**Comment by CDeenen** [comment]
Removed the empty line after 'round' in v1.4.5. I think the space after 'turn' is an alignment issue that I cannot fix (it's something the Stream Deck does)
